#!venv/bin/python
"""
Do requests do a URL using proxy list generated by get_openproxy
Author: Paulo Coimbra
Date: 2025-07-25

"""
import sys
from concurrent.futures import ThreadPoolExecutor, as_completed

import requests


def usage():
	print('Usage:')
	print (f'{sys.argv[0]} <URL> <PROXY LIST>')


def debug(title,msg):
	print(f'-------------[ {title} ]-------------')
	print(msg)

def load_proxies(proxy_file):
	try:
		with open(proxy_file,'r') as file:
			proxies=[]
			for line in file.readlines():
				proxy=line.strip('\n')
				proxies.append(proxy)
		file.close()
		return proxies

	except Exception as error:
		debug("An error was occurred",error)


def do_request(url,proxy):
	try:
		print(proxy)
		response = requests.get(
			url,
			proxies={
			'http': f'{proxy}',
			'https': f'{proxy}'
			 },
			timeout=3
		)
		return(f'Proxy OK -> {proxy} -> STATUS: {response.status_code}')
	except:
		PROXIES.remove(proxy)
		return (f'Bad Proxy -> {proxy}. Removing entry...')


def save_working_proxies(proxies, file):
	with open(file,'w') as file:
		for proxy in proxies:
			file.write(f'{proxy}\n')
	file.close()


if __name__ == '__main__':
	if len(sys.argv) != 3:
		usage()
		exit(1)
	URL=sys.argv[1]
	PROXY_FILE=sys.argv[2]
	PROXIES=load_proxies(PROXY_FILE)
	num_threads=15

	with ThreadPoolExecutor(max_workers=num_threads) as executor:
		futures = [executor.submit(do_request, URL, proxy) for proxy in PROXIES]
		for future in as_completed(futures):
			print(future.result())

	save_working_proxies(PROXIES, PROXY_FILE)
